name: Debug Session

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup custom prompt
         run: |
               export PS1="\[\e[92m\]\u@Jonjeexe \$ \[\e[97m\]-/\W \[\e[0m\]"
               bash --login
    
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
